stages:
    - buildimages
    - createPUfile
    - runCode
    - makePlots

variables:
    inputFile : datasets/datasets_btag2017.json
    coffeaFile : hists_fattag_flavor_mutag_2017.coffea7
    year: 2017

.docker_build:
    image:
        name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
        entrypoint: [""]
    script:
        # Prepare Kaniko configuration file
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        # Build and push the image from the Dockerfile at the root of the project.
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/$dockerfile --destination $IMAGE_DESTINATION
        # Print the full registry path of the pushed image
        - echo "Image pushed successfully to ${IMAGE_DESTINATION}"

build_image:
    stage: buildimages
    extends: .docker_build
    variables:
        IMAGE_DESTINATION: $CI_REGISTRY_IMAGE:latest
        #IMAGE_DESTINATION: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
        dockerfile: Dockerfile

build_combine:
    stage: buildimages
    extends: .docker_build
    image:
        entrypoint: ["/home/cmsusr/"]
    tags:
        - cvmfs
    variables:
        IMAGE_DESTINATION: ${CI_REGISTRY_IMAGE}:combine
        dockerfile: DockerfileCombine

#build_combine:
#    stage: build
#    image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_2_21-slc7_amd64_gcc700:2020-09-22-ef834977
#    tags:
#        - cvmfs
#    script:
#        - cd /home/cmsusr/CMSSW_10_2_21/src/
#        - eval `scramv1 runtime -sh`
#        - git clone https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit.git HiggsAnalysis/CombinedLimit 
#        - cd HiggsAnalysis/CombinedLimit/  
#        - git fetch origin 
#        - git checkout v8.2.0 
#        - cd $CMSSW_BASE/src/
#        - /cvmfs/cms.cern.ch/common/scramv1 b clean
#        - /cvmfs/cms.cern.ch/common/scramv1 b 
#        - eval `scramv1 runtime -sh`
#        - pip3 install --upgrade pip --user
#        - pip3 install flake8 --user
#        - pip3 install --user https://github.com/nsmith-/rhalphalib/archive/master.zip

voms_proxy:
    stage: buildimages 
    image: gitlab-registry.cern.ch/clange/grid-proxy-test:master
    artifacts:
        paths:
            - proxy
    script:
        - mkdir -p ${HOME}/.globus
        - printf "${GRID_USERCERT}" | base64 -d > ${HOME}/.globus/usercert.pem
        - printf "${GRID_USERKEY}" | base64 -d > ${HOME}/.globus/userkey.pem
        - chmod 400 ${HOME}/.globus/userkey.pem
        - printf "${GRID_PASSWORD}" | base64 -d | voms-proxy-init --voms cms --pwstdin
        - voms-proxy-info --all
        - export VOMSPROXY=$(voms-proxy-info -path)
        - mkdir proxy
        - cp ${VOMSPROXY} proxy/x509_proxy

runPU:
    dependencies:
        - voms_proxy
    stage: createPUfile
    tags:
        - cvmfs
    image: $CI_REGISTRY_IMAGE:latest
    #image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    script:
        - export X509_USER_PROXY=${PWD}/proxy/x509_proxy
        - mkdir test
        - python createNTrueForPU.py --samples "${inputFile}" --year "${year}" --outputDir test --outputName testFile.coffea
    artifacts:
        expire_in: 1 day
        paths:
            - test

runcode:
    dependencies:
        - voms_proxy
        - runPU
    stage: runCode
    tags:
        - cvmfs
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - export X509_USER_PROXY=${PWD}/proxy/x509_proxy
        - pwd -LP
        - python simplerunner.py --workflow fattag --executor futures --samples "${inputFile}" --output "${coffeaFile}" --year "${year}" --limit 5 --nTrueFile test/testFile.coffea
    artifacts:
        expire_in: 1 day
        paths:
            - histograms 

runplots:
    dependencies:
        - runcode
    stage: makePlots
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - python make_plots_simple.py -i ${PWD}/histograms/"${coffeaFile}" --outputDir ${PWD}/plots/ -d --year "${year}" --selection msd100tau06 --test
    artifacts:
        expire_in: 1 week
        paths:
            - plots

createPickleFile:
    dependencies:
        - runcode
    stage: makePlots
    image: $CI_REGISTRY_IMAGE:latest
    script:
        - python coffeaToPickle.py -i ${PWD}/histograms/"${coffeaFile}" --year "{year}" --outputDir ${PWD}/pickleFiles/
    artifacts:
        expire_in: 1 day
        paths:
            - pickleFiles

