stages:
- name: runpu
  dependencies: [init]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFile: {step: init, output: inputFile, unwrap: true}
          year: {step: init, output: year, unwrap: true}
          workingdir: '$REANA_WORKSPACE'
          outputFile: 'nTrueFile.coffea'
      step: {$ref: 'reana_workflows/steps.yaml#/runpu'}

- name: runcode
  dependencies: [runpu]
  scheduler:
      scheduler_type: 'multistep-stage'
      parameters:
          inputFile: {step: init, output: inputFile, unwrap: true}
          dataset: {step: init, output: datasets, unwrap: true}
          year: {step: init, output: year, unwrap: true}
          workingdir: '$REANA_WORKSPACE/'
          nTrueFile: {stages: runpu, output: outputCoffea}
          outputFile: '{workdir}/coffeaFile.coffea7'
          outputdir: '{workdir}/histograms/'
      scatter:
          method: zip
          parameters: [dataset]
      step: {$ref: 'reana_workflows/steps.yaml#/runcode'}

- name: makeplots
  dependencies: [runcode]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFolder: {stages: runcode, output: output_dir}
          year: {step: init, output: year, unwrap: true}
          workingdir: '$REANA_WORKSPACE/'
          outputtar: '{workdir}/plots.tar'
      step: {$ref: 'reana_workflows/steps.yaml#/makeplots'}

- name: createPickleFile
  dependencies: [runcode]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFolder: {stages: runcode, output: output_dir}
          year: {step: init, output: year, unwrap: true}
          workingdir: '$REANA_WORKSPACE/'
          outputfile: 'hists_fattag.pkl'
      step: {$ref: 'reana_workflows/steps.yaml#/createpickle'}

- name: runCombine
  dependencies: [createPickleFile]
  scheduler:
      scheduler_type: 'multistep-stage'
      parameters:
          inputFile: {stages: createPickleFile, output: picklefile, wrap: true}
          wp: {step: init, output: workingpoints, wrap: true}
          workingdir: '$REANA_WORKSPACE/'
      scatter:
          method: zip
          parameters: [wp]
      step: {$ref: 'reana_workflows/steps.yaml#/runcombine'}
