stages:
- name: runpu
  dependencies: [init]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFile: {step: init, output: inputFile}
          year: {step: init, output: year}
          workingdir: '$REANA_WORKSPACE'
          outputFile: 'nTrueFile.coffea'
      step: {$ref: 'reana_workflows/steps.yaml#/runpu'}

- name: runcode
  dependencies: [runpu]
  scheduler:
      scheduler_type: 'multistep-stage'
      parameters:
          inputFile: {stages: init, output: inputFile, unwrap: true}
          dataset: {stages: init, output: datasets, unwrap: true}
          year: {stages: init, output: year, unwrap: true}
          workingdir: '$REANA_WORKSPACE/'
          nTrueFile: {stages: runpu, output: outputCoffea}
          outputFile: '{workdir}/coffeaFile.coffea7'
      scatter:
          method: zip
          parameters: [dataset]
      step: {$ref: 'reana_workflows/steps.yaml#/runcode'}

- name: makeplots
  dependencies: [runcode]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFile: {step: runcode, output: output_files, flatten: true}
          year: {step: init, output: year}
          workingdir: '$REANA_WORKSPACE/'
      step: {$ref: 'reana_workflows/steps.yaml#/makeplots'}

- name: createPickleFile
  dependencies: [runcode]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFile: {step: runcode, output: output_files, flatten: true}
          year: {step: init, output: year}
          workingdir: '$REANA_WORKSPACE/'
          outputfile: 'hists_fattag.pkl'
      step: {$ref: 'reana_workflows/steps.yaml#/createpickle'}

- name: runCombine
  dependencies: [createPickleFile]
  scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
          inputFile: {step: createPickleFile, output: picklefile}
          year: {step: init, output: year}
          workingdir: '$REANA_WORKSPACE/'
      step: {$ref: 'reana_workflows/steps.yaml#/runcombine'}
